package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Repo3'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Repo3")
    name = "repo3"
    url = "git@github.com:ChubatovaTiger/repo3.git"
    branch = "refs/heads/main"
    authMethod = uploadedKey {
        uploadedKey = "rsaopensshnew"
        passphrase = "credentialsJSON:92710fb4-18c3-40fe-a2fa-1b14c42b8014"
    }
}))

